ARG IMAGE_FROM
FROM ${IMAGE_FROM}

RUN apt-get -y install git curl gnupg && \
        curl -sL https://deb.nodesource.com/setup_12.x  | bash && \
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
        apt-get -y update && \
        apt-get -y install nodejs yarn
